apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-dep
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps:jmogo
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 11111
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.49.112
  selector:
    app: ftps
  ports:
  - port: 21
    name: https
    protocol: TCP
    targetPort: 21
  - port: 11111
    name: psv
    protocol: TCP
    targetPort: 11111
