apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dep
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana:jmogo
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.49.112
  selector:
    app: grafana
  ports:
  - port: 3000
    name: graf
    protocol: TCP
    targetPort: 3000
