apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:jmogo
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.49.130
  selector:
    app: nginx
  ports:
    - port: 80
      name: nginx-http
      protocol: TCP
      targetPort: 80
    - port: 443
      name: nginx-https
      protocol: TCP
      targetPort: 443
    - port: 22
      name: nginx-ssh
      protocol: TCP
      targetPort: 22
