apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data
  labels:
    type: local
spec:
  storageClassName: mysql-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-data
  labels:
    type: local
spec:
  storageClassName: influxdb-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate
