apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:jmogo
          imagePullPolicy: Never
          ports:
          - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.49.112
  selector:
    app: wordpress
  ports:
    - name: wp
      protocol: TCP
      port: 5050
      targetPort: 5050
